import 'package:ai_powered_tourists_app/features/profile/screen/quize_options.dart';
import 'package:ai_powered_tourists_app/utils/constants/image_path.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
class PlayAiQuize extends StatelessWidget {
  const PlayAiQuize({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xffF9F9F9),
      body: Padding(
        padding:  EdgeInsets.symmetric(horizontal: 12.w),
        child: Column(
         mainAxisAlignment: MainAxisAlignment.center,
         crossAxisAlignment: CrossAxisAlignment.start,
          children: [
          
            Center(
              child: Image(image: AssetImage(ImagePath.aiball),width: 180.w,height: 180.h,fit: BoxFit.cover,),
            ),
            Center(
              child: Text("Test Your Travel Knowledge",style: GoogleFonts.inter( 
                fontSize: 20.sp,
                fontWeight: FontWeight.w600,
                color: Color(0xff252525)
              ),),
            ),
            SizedBox(height: 4.h,),
            Center(
              child: Text("Fun quizzes generated by AI, based on ",style: GoogleFonts.inter( 
                 fontSize: 16.sp,
                fontWeight: FontWeight.w400,
                color: Color(0xff878787)
              ),),
            ),
                  SizedBox(height: 4.h,),
            Center(
              child: Text("the places you explore",style: GoogleFonts.inter( 
                 fontSize: 16.sp,
                fontWeight: FontWeight.w400,
                color: Color(0xff878787)
              ),),
            ),
            SizedBox(height: 29.h,),
          InkWell(
                onTap: () {
                Get.to(()=>QuizeOptions());
                },
                child: Container(
                  width: double.infinity,
                  height: 48.h,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(12.r),
                    image: const DecorationImage(
                      image: AssetImage(ImagePath.button), // তোমার ইমেজ path
                      fit: BoxFit.cover,
                    ),
                  ),
                  child: Center(
                    child: Text(
                      "Start AI Quiz",
                      style: GoogleFonts.inter(
                        fontSize: 20.sp,
                        fontWeight: FontWeight.w600,
                        color: Colors.white,
                        shadows: [
                          Shadow(
                            offset: const Offset(0, 1),
                            blurRadius: 4,
                            color: Colors.black.withValues(alpha: .4),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
        
          ],
        ),
      ),
    );
  }
}